version: '3'
services: 
  # Setup client container
  frontend:
    build: ./view
    container_name: image-detect-client
    command: npm run serve
    ports: 
      - 8080:8080
    volumes: 
      - .:/usr/src/app/client
    
  # Setup server container
  backend:
    build: ./server
    container_name: image-detect-server
    command: npm run prod
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/src/app/server